[package]
name = "aoc-bud"
version = "0.0.1"
edition = "2021"

authors = ["no0bie"]
description = "A advent of code rust helper"

include = ["**/*.rs", "Cargo.toml"]

[dependencies]
chrono = "0.4.23"
dotenv = "0.15.0"
reqwest = {version = "0.11.13", features = ["blocking"]}